### ISSUE TITLE
Module 1 exercises [Ebenezer Kwanin]

### ISSUE THREAD

**Issue by ekwanin** [ernest19/SNV#10]
1. Please  copy and paste  the link to you script here
https://code.earthengine.google.com/309bf9c7bdedbd1ec381563d309e6ff4

**Comment by ernest19** [comment]
Well done, Ebenezer. Your solution looks great, and it is clear that you understand the material in Module 1 and can successfully apply it to the subsequent modules. Thanks for your participation!
