### ISSUE TITLE
Module 1 exercises [S.A. Andam-Akorful]

### ISSUE THREAD

**Issue by deepseaz** [ernest19/SNV#11]
1. Please  copy and paste  the link to you script here[https://code.earthengine.google.com/5fda60c21cbbe04899bdd311206763eb](url)

**Comment by deepseaz** [comment]
https://code.earthengine.google.com/5fda60c21cbbe04899bdd311206763eb

**Comment by ernest19** [comment]
Well done, Ebenezer. Your solution looks great, and it is clear that you understand the material in Module 1 and can successfully apply it to the subsequent modules. Thanks for your participation!
