### ISSUE TITLE
Module 1 exercises [Marvin Robert Adjetey Mohenu]

### ISSUE THREAD

**Issue by marvinrobert** [ernest19/SNV#2]
1. Please  copy and paste  the link to you script here
[https://code.earthengine.google.com/1878cfad1cbe0aeb7dbd0f893849b00b](url)

**Comment by ernest19** [comment]
Well done, Marvin. Your solution looks great, and it is clear that you understand the material in Module 1 and can successfully apply it to the subsequent modules. Thanks for your participation!
