### ISSUE TITLE
Module 1 exercises [William Odoi]

### ISSUE THREAD

**Issue by burntspy** [ernest19/SNV#4]
https://code.earthengine.google.com/fed8d0d52acb54caecad3ab702a370ad

**Comment by burntspy** [comment]
https://code.earthengine.google.com/fed8d0d52acb54caecad3ab702a370ad

**Comment by ernest19** [comment]
Well done, William. Your solution looks great, and it is clear that you understand the material in Module 1 and can successfully apply it to the subsequent modules. Thanks for your participation!
